import type { TierId } from '../../engine/generator/tiers/tiers.ts'
import type { LabPhase } from './protocol.ts'

/** English wording of the puzzle lab (dev only). */
export const LAB_EN = {
  title: 'Puzzle lab',
  subtitle: 'For developers only: browse, generate and test puzzles.',
  toGame: 'To the game',
  levelsTitle: 'Levels',
  columns: { id: 'Id', title: 'Title', size: 'Size', tier: 'Difficulty', theme: 'Theme', clues: 'Clues', score: 'Score' },
  open: 'Play',
  tier: {
    'very-easy': 'Very easy',
    easy: 'Easy',
    'easy-medium': 'Easy-medium',
    medium: 'Medium',
    hard: 'Hard',
    expert: 'Expert',
  } satisfies Record<TierId, string>,
  size_: (n: number) => `${n}x${n}`,

  generate: {
    title: 'Generate a puzzle',
    size: 'Size',
    tier: 'Difficulty',
    theme: 'Theme',
    seed: 'Seed',
    seedHint: 'The same size, theme, difficulty and seed give the same puzzle.',
    randomSeed: 'Random seed',
    victim: 'Victim on square (optional)',
    victimRow: 'Row',
    victimCol: 'Column',
    victimHint: 'Leave empty for a random square. Row and column count from 1.',
    budget: 'Maximum search time (seconds)',
    submit: 'Generate',
    cancel: 'Cancel',
    running: 'Generating...',
    cancelled: 'Cancelled.',
    phase: {
      scene: 'Building the floor plan',
      search: 'Searching for clues',
      check: 'Checking the puzzle',
    } satisfies Record<LabPhase, string>,
    elapsed: (seconds: number, budget: number) => `${seconds} s of at most ${budget} s`,
    resultTitle: 'Result',
    resultOk: (id: string) => `Done: ${id}`,
    resultDetails: (attempts: number, ms: number, clues: number, score: number) =>
      `${clues} clues, score ${score}, ${attempts} attempt${attempts === 1 ? '' : 's'}, ${(ms / 1000).toFixed(1)} s`,
    failTitle: 'Failed',
    failTimedOut: 'The search time ran out.',
    failAttempts: (attempts: number) => `${attempts} placement${attempts === 1 ? '' : 's'} tried.`,
    failRejections: 'Rejected by',
    warningsTitle: 'Note: the puzzle does not pass all pack checks',
    playGenerated: 'Play this puzzle',
    errors: {
      seed: 'The seed must be a whole number, 0 or higher.',
      budget: 'The search time must be between 5 and 600 seconds.',
      victimBoth: 'Fill in both row and column, or leave both empty.',
      victimRange: (size: number) => `Row and column must be between 1 and ${size}.`,
    },
    workerFailed: 'The background task stopped with an error',
  },

  play: {
    back: 'Back to the lab',
    restart: 'Start over',
    copy: 'Copy puzzle JSON',
    copied: 'Copied',
    copyFailed: 'Copying failed',
    verifyTitle: 'Check: unique solution',
    pass: 'PASSED',
    fail: 'FAILED',
    solutions: (count: number) => (count > 1 ? `${count}+ solutions` : `${count} solution${count === 1 ? '' : 's'}`),
    murderer: (id: string) => `Murderer: ${id}`,
    notFound: 'This puzzle does not exist.',
    loading: 'Loading puzzle...',
    loadFailed: 'The puzzle could not be loaded.',
    noGenerated: 'There is no generated puzzle yet. Generate one first.',
    source: { level: 'Level', generated: 'Generated' },
    score: (n: number) => `score ${n}`,
    clues: (n: number) => `${n} clues`,
    tabs: { label: 'View', play: 'Play', insight: 'Insight' },
  },

  insight: {
    computing: 'Calculating...',
    failed: 'The insight could not be calculated.',
    scoreTitle: 'Difficulty score v2',
    scoreIntro: 'Every measurement becomes a share from 0 to 100%; the score is the weighted average of those shares.',
    scoreResult: (score: number) => `Score: ${score} of 100 (higher is harder)`,
    columns: { metric: 'Measurement', value: 'Value', part: 'Share', weight: 'Weight' },
    yes: 'Yes',
    no: 'No',
    noPart: '-',
    metrics: {
      people: 'People',
      clueCount: 'Clues',
      solved: 'Solvable without guessing',
      steps: 'Steps',
      longestChain: 'Longest chain of reasoning',
      cluesPerStep: 'Cards per step (average)',
      directClueShare: 'Share of direct cards',
      candidatesPerStep: 'Open squares per step (average)',
      hardestLevel: 'Hardest technique (level 1 to 5)',
      ladderSolved: 'Placeable one by one (without the hard techniques)',
      cardsPerPlacement: 'Cards per placement (average)',
      referenceShare: 'Share of placements with a card about somebody else',
      squaresFromCards: 'Squares the cards leave (average)',
      ladderChain: 'Placements waiting on each other (average)',
      placeableAloneShare: 'Share that can be placed with their own card alone',
    },
    traceTitle: 'Solution step by step',
    traceIntro: 'What a practiced player does, with the three hint texts as the game gives them. Squares: r = row, c = column.',
    traceEmpty: 'No steps are needed.',
    traceUnsolved: 'Note: this puzzle cannot be solved without guessing; the list only shows the steps that were found.',
    step: (n: number) => `Step ${n}`,
    level: (n: number) => `level ${n}`,
    cells: 'Squares',
    cellCount: (n: number) => `${n} square${n === 1 ? '' : 's'}`,
    places: 'Places',
    hint: (level: number) => `Hint ${level}`,
    telemetryTitle: 'Play data',
    telemetryNote: 'Sessions from the game on this device (same browser and address). Playing in the lab does not count.',
    telemetryEmpty: 'No play data for this puzzle yet.',
    summary: {
      sessions: 'Sessions',
      solvedOf: (solved: number, abandoned: number) => `${solved} solved, ${abandoned} unfinished`,
      medianTime: 'Median time (solved)',
      medianHints: 'Median hints per session',
      medianErrors: 'Median mistakes per session',
      none: '-',
    },
    records: {
      started: 'Started',
      time: 'Time',
      hints: 'Hints 1 / 2 / 3',
      hintPlacements: 'Placed by hint',
      wrong: 'Placed wrong',
      failedChecks: 'Failed checks',
      undos: 'Undos',
      outcome: 'Outcome',
      solved: 'Solved',
      abandoned: 'Unfinished',
    },
    exportTelemetry: 'Export all play data (JSON)',
    judgementTitle: 'Your verdict',
    judgementIntro: 'Optional: how hard does this puzzle feel? Saved on this device.',
    verdicts: { 'too-easy': 'Too easy', good: 'Good', 'too-hard': 'Too hard' },
    noVerdict: 'No verdict',
    judgedAs: (label: string, when: string) => `Saved: ${label} (${when})`,
    notJudged: 'No verdict given yet.',
    saveFailed: 'Saving failed: the browser gives no storage.',
    transferTitle: 'Share verdicts',
    judgedCount: (n: number) => (n === 1 ? '1 puzzle judged' : `${n} puzzles judged`),
    exportJudgements: 'Export verdicts (JSON)',
    importJudgements: 'Import verdicts (JSON file)',
    imported: (n: number, skipped: number) =>
      `${n} ${n === 1 ? 'verdict' : 'verdicts'} imported${skipped > 0 ? `, ${skipped} skipped` : ''}.`,
    importFailed: 'This is not a valid verdicts file. Nothing was changed.',
  },
} as const
