import type { TierId } from '../../engine/generator/tiers/tiers.ts'
import type { LabPhase } from './protocol.ts'

/** Dutch wording of the puzzle lab (dev only). */
export const LAB_NL = {
  title: 'Puzzellab',
  subtitle: 'Alleen voor de ontwikkelaar: bekijk, genereer en test puzzels.',
  toGame: 'Naar het spel',
  levelsTitle: 'Levels',
  columns: { id: 'Id', title: 'Titel', size: 'Formaat', tier: 'Moeilijkheid', theme: 'Thema', clues: 'Aanwijzingen', score: 'Score' },
  open: 'Speel',
  tier: {
    'very-easy': 'Zeer makkelijk',
    easy: 'Makkelijk',
    'easy-medium': 'Makkelijk-gemiddeld',
    medium: 'Gemiddeld',
    hard: 'Moeilijk',
    expert: 'Expert',
  } satisfies Record<TierId, string>,
  size_: (n: number) => `${n}x${n}`,

  generate: {
    title: 'Puzzel genereren',
    size: 'Formaat',
    tier: 'Moeilijkheid',
    theme: 'Thema',
    seed: 'Seed',
    seedHint: 'Hetzelfde formaat, thema, moeilijkheid en seed geeft dezelfde puzzel.',
    randomSeed: 'Willekeurige seed',
    victim: 'Cadeau op vak (optioneel)',
    victimRow: 'Rij',
    victimCol: 'Kolom',
    victimHint: 'Laat leeg voor een willekeurig vak. Rij en kolom tellen vanaf 1.',
    budget: 'Maximale zoektijd (seconden)',
    submit: 'Genereer',
    cancel: 'Annuleer',
    running: 'Bezig met genereren...',
    cancelled: 'Geannuleerd.',
    phase: {
      scene: 'Plattegrond maken',
      search: 'Aanwijzingen zoeken',
      check: 'Puzzel controleren',
    } satisfies Record<LabPhase, string>,
    elapsed: (seconds: number, budget: number) => `${seconds} s van maximaal ${budget} s`,
    resultTitle: 'Resultaat',
    resultOk: (id: string) => `Gelukt: ${id}`,
    resultDetails: (attempts: number, ms: number, clues: number, score: number) =>
      `${clues} aanwijzingen, score ${score}, ${attempts} poging${attempts === 1 ? '' : 'en'}, ${(ms / 1000).toFixed(1)} s`,
    failTitle: 'Mislukt',
    failTimedOut: 'De zoektijd was op.',
    failAttempts: (attempts: number) => `${attempts} plaatsing${attempts === 1 ? '' : 'en'} geprobeerd.`,
    failRejections: 'Afgewezen door',
    warningsTitle: 'Let op: de puzzel voldoet niet aan alle pack-controles',
    playGenerated: 'Speel deze puzzel',
    errors: {
      seed: 'De seed moet een geheel getal van 0 of hoger zijn.',
      budget: 'De zoektijd moet tussen 5 en 600 seconden liggen.',
      victimBoth: 'Vul zowel rij als kolom in, of laat beide leeg.',
      victimRange: (size: number) => `Rij en kolom moeten tussen 1 en ${size} liggen.`,
    },
    workerFailed: 'De achtergrondtaak is gestopt met een fout',
  },

  play: {
    back: 'Terug naar het lab',
    restart: 'Opnieuw beginnen',
    copy: 'Kopieer puzzel-JSON',
    copied: 'Gekopieerd',
    copyFailed: 'Kopieren niet gelukt',
    verifyTitle: 'Controle: unieke oplossing',
    pass: 'GESLAAGD',
    fail: 'MISLUKT',
    solutions: (count: number) => (count > 1 ? `${count}+ oplossingen` : `${count} oplossing${count === 1 ? '' : 'en'}`),
    murderer: (id: string) => `Dader: ${id}`,
    notFound: 'Deze puzzel bestaat niet.',
    loading: 'Puzzel laden...',
    loadFailed: 'De puzzel kon niet worden geladen.',
    noGenerated: 'Er is nog geen gegenereerde puzzel. Genereer er eerst een.',
    source: { level: 'Level', generated: 'Gegenereerd' },
    score: (n: number) => `score ${n}`,
    clues: (n: number) => `${n} aanwijzingen`,
    tabs: { label: 'Weergave', play: 'Spelen', insight: 'Inzicht' },
  },

  insight: {
    computing: 'Bezig met berekenen...',
    failed: 'Het inzicht kon niet worden berekend.',
    scoreTitle: 'Moeilijkheidsscore v2',
    scoreIntro: 'Elke meting wordt een deel van 0 tot 100%; de score is het gewogen gemiddelde van die delen.',
    scoreResult: (score: number) => `Score: ${score} van 100 (hoger is moeilijker)`,
    columns: { metric: 'Meting', value: 'Waarde', part: 'Deel', weight: 'Gewicht' },
    yes: 'Ja',
    no: 'Nee',
    noPart: '-',
    metrics: {
      people: 'Personen',
      clueCount: 'Aanwijzingen',
      solved: 'Zonder gokken op te lossen',
      steps: 'Stappen',
      longestChain: 'Langste redeneerketen',
      cluesPerStep: 'Kaarten per stap (gemiddeld)',
      directClueShare: 'Aandeel directe kaarten',
      candidatesPerStep: 'Open vakjes per stap (gemiddeld)',
      hardestLevel: 'Zwaarste techniek (niveau 1 tot 5)',
      ladderSolved: 'Een voor een neer te zetten (zonder de zware technieken)',
      cardsPerPlacement: 'Kaarten per neerzetting (gemiddeld)',
      referenceShare: 'Aandeel neerzettingen met een kaart over een ander',
      squaresFromCards: 'Vakjes die de kaarten laten (gemiddeld)',
      ladderChain: 'Neerzettingen die op elkaar wachten (gemiddeld)',
      placeableAloneShare: 'Aandeel dat met de eigen kaart alleen te plaatsen is',
    },
    traceTitle: 'Oplossing stap voor stap',
    traceIntro: 'Wat een geoefende speler doet, met de drie hint-teksten zoals het spel ze geeft. Vakjes: r = rij, k = kolom.',
    traceEmpty: 'Er zijn geen stappen nodig.',
    traceUnsolved: 'Let op: deze puzzel is niet zonder gokken op te lossen; de lijst toont alleen de stappen die wel gevonden zijn.',
    step: (n: number) => `Stap ${n}`,
    level: (n: number) => `niveau ${n}`,
    cells: 'Vakjes',
    cellCount: (n: number) => `${n} vakjes`,
    places: 'Zet neer',
    hint: (level: number) => `Hint ${level}`,
    telemetryTitle: 'Speelgegevens',
    telemetryNote: 'Sessies uit het spel op dit apparaat (zelfde browser en adres). Spelen in het lab telt niet mee.',
    telemetryEmpty: 'Nog geen speelgegevens voor deze puzzel.',
    summary: {
      sessions: 'Sessies',
      solvedOf: (solved: number, abandoned: number) => `${solved} opgelost, ${abandoned} niet af`,
      medianTime: 'Mediaan tijd (opgelost)',
      medianHints: 'Mediaan hints per sessie',
      medianErrors: 'Mediaan fouten per sessie',
      none: '-',
    },
    records: {
      started: 'Gestart',
      time: 'Tijd',
      hints: 'Hints 1 / 2 / 3',
      hintPlacements: 'Geplaatst door hint',
      wrong: 'Fout geplaatst',
      failedChecks: 'Foute controles',
      undos: 'Herstel',
      outcome: 'Uitkomst',
      solved: 'Opgelost',
      abandoned: 'Niet af',
    },
    exportTelemetry: 'Exporteer alle speelgegevens (JSON)',
    judgementTitle: 'Jouw oordeel',
    judgementIntro: 'Optioneel: hoe zwaar voelt deze puzzel? Wordt op dit apparaat bewaard.',
    verdicts: { 'too-easy': 'Te makkelijk', good: 'Goed', 'too-hard': 'Te moeilijk' },
    noVerdict: 'Geen oordeel',
    judgedAs: (label: string, when: string) => `Bewaard: ${label} (${when})`,
    notJudged: 'Nog geen oordeel gegeven.',
    saveFailed: 'Bewaren is niet gelukt: de browser geeft geen opslag.',
    transferTitle: 'Oordelen delen',
    judgedCount: (n: number) => (n === 1 ? '1 puzzel beoordeeld' : `${n} puzzels beoordeeld`),
    exportJudgements: 'Exporteer oordelen (JSON)',
    importJudgements: 'Importeer oordelen (JSON-bestand)',
    imported: (n: number, skipped: number) =>
      `${n} ${n === 1 ? 'oordeel' : 'oordelen'} geïmporteerd${skipped > 0 ? `, ${skipped} overgeslagen` : ''}.`,
    importFailed: 'Dit is geen geldig bestand met oordelen. Er is niets veranderd.',
  },
} as const
