import { lShape, rect } from '../../../src/content/themes/define.ts'
import type { SeasonalTheme } from './common.ts'

/** Christmas: all of December, so it has plenty of rooms (18). Santa's village, a chapel, a market and the snow outside. */
export const CHRISTMAS_THEME: SeasonalTheme = {
  id: 'christmas',
  name: "Santa's village",
  nameNl: 'Het dorp van de Kerstman',
  season: 'December',
  seasonNl: 'December',
  blurb: 'A workshop, stable, market and chapel under snow: trees, presents, a sleigh, reindeer and gingerbread.',
  rooms: [
    { name: "Santa's Workshop", nameNl: 'Kerstmanwerkplaats', favours: ['workbench', 'toyShelf', 'present', 'toyChest'], roomTypes: ['workshop'], floor: 'wood' },
    { name: 'Toy Room', nameNl: 'Speelgoedkamer', favours: ['rockingHorse', 'toyShelf', 'toyChest', 'furRug'], roomTypes: ['workshop', 'sleeping'], floor: 'carpet' },
    { name: 'Wrapping Room', nameNl: 'Inpakkamer', favours: ['present', 'workbench', 'armchair'], roomTypes: ['workshop'], floor: 'carpet' },
    { name: 'Letter Room', nameNl: 'Brievenkamer', favours: ['workbench', 'armchair', 'toyShelf'], roomTypes: ['study'], floor: 'wood' },
    { name: 'Gingerbread Kitchen', nameNl: 'Peperkoekkeuken', favours: ['counter', 'gingerbreadHouse', 'longTable', 'cupboard'], roomTypes: ['kitchen'], floor: 'tiles' },
    { name: 'Dining Room', nameNl: 'Eetkamer', favours: ['longTable', 'armchair', 'christmasTree', 'fireplace'], roomTypes: ['dining'], floor: 'wood' },
    { name: 'Fireside Lounge', nameNl: 'Haardkamer', favours: ['fireplace', 'sofa', 'christmasTree', 'furRug'], roomTypes: ['living'], floor: 'wood' },
    { name: "Children's Bedroom", nameNl: 'Kinderslaapkamer', favours: ['bed', 'toyChest', 'rockingHorse', 'wardrobe'], roomTypes: ['sleeping'], floor: 'carpet' },
    { name: 'Elf Dormitory', nameNl: 'Elfenslaapzaal', favours: ['bed', 'wardrobe', 'toyChest'], roomTypes: ['sleeping'], floor: 'carpet' },
    { name: 'Attic', nameNl: 'Zolder', favours: ['toyChest', 'present', 'wardrobe', 'stairs'], roomTypes: ['storage'], floor: 'wood' },
    { name: 'Reindeer Stable', nameNl: 'Rendierstal', favours: ['reindeer', 'hayBale', 'bench'], roomTypes: ['stable'], floor: 'stone' },
    { name: 'Sleigh Shed', nameNl: 'Sleeschuur', favours: ['sleigh', 'present', 'hayBale'], roomTypes: ['garage'], floor: 'stone' },
    { name: 'Snowy Garden', nameNl: 'Besneeuwde tuin', favours: ['snowman', 'firTree', 'holly', 'bench'], roomTypes: ['outdoor'], outdoor: true, floor: 'water' },
    { name: 'Snowman Meadow', nameNl: 'Sneeuwmanweide', favours: ['snowman', 'firTree', 'sleigh'], roomTypes: ['outdoor'], outdoor: true, floor: 'water' },
    { name: 'Ice Rink', nameNl: 'Ijsbaan', favours: ['bench', 'christmasTree', 'snowman'], roomTypes: ['outdoor'], outdoor: true, floor: 'water' },
    { name: 'Christmas Market', nameNl: 'Kerstmarkt', favours: ['marketTable', 'christmasTree', 'gingerbreadHouse', 'counter'], roomTypes: ['market', 'outdoor'], outdoor: true, floor: 'stone' },
    { name: 'Hot Chocolate Bar', nameNl: 'Chocolademelkbar', favours: ['counter', 'armchair', 'marketTable', 'christmasTree'], roomTypes: ['party'], floor: 'tiles' },
    { name: 'Chapel', nameNl: 'Kapel', favours: ['bench', 'christmasTree', 'poinsettia'], roomTypes: ['chapel'], floor: 'stone' },
  ],
  objects: [
    // Occupiable
    { kind: 'armchair', name: 'armchair', engineType: 'chair', weight: 8, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['living', 'dining', 'study', 'workshop', 'kitchen', 'party'] },
    { kind: 'rockingHorse', name: 'rocking horse', engineType: 'chair', themeIcon: 'rockingHorse', weight: 2, footprints: [rect(1, 1)], placement: 'anywhere', maxPerRoom: 2, allowedRoomTypes: ['workshop', 'sleeping', 'living'] },
    { kind: 'hayBale', name: 'hay bale', engineType: 'rug', themeIcon: 'hayBale', weight: 5, footprints: [rect(1, 1), rect(2, 1, 0.7), rect(2, 2, 0.4)], placement: 'anywhere', allowedRoomTypes: ['stable', 'garage'] },
    { kind: 'furRug', name: 'fur rug', engineType: 'rug', weight: 4, footprints: [rect(2, 1), rect(2, 2, 0.5), rect(1, 1, 0.4)], placement: 'centre', allowedRoomTypes: ['living', 'sleeping', 'dining', 'workshop'] },
    { kind: 'bed', name: 'bed', engineType: 'bed', weight: 3, footprints: [rect(1, 2), rect(2, 2, 0.5)], placement: 'wall', maxPerRoom: 2, allowedRoomTypes: ['sleeping'] },
    { kind: 'sofa', name: 'sofa', engineType: 'sofa', weight: 3, footprints: [rect(2, 1), rect(3, 1), lShape(2, 0.5)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['living', 'party'] },
    { kind: 'sleigh', name: 'sleigh', engineType: 'car', themeIcon: 'sleigh', weight: 2, footprints: [rect(1, 2)], placement: 'wall', maxPerRoom: 2, allowedRoomTypes: ['garage', 'outdoor'], excludeRoomTypes: ['sleeping'] },
    // Blocking
    { kind: 'christmasTree', name: 'Christmas tree', clueNoun: 'Christmas tree', engineType: 'tree', themeIcon: 'christmasTree', weight: 6, footprints: [rect(1, 1)], placement: 'anywhere', maxPerRoom: 2, allowedRoomTypes: ['living', 'dining', 'market', 'chapel', 'party', 'outdoor'] },
    { kind: 'firTree', name: 'fir tree', engineType: 'tree', weight: 6, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['outdoor'] },
    { kind: 'present', name: 'present', engineType: 'chest', themeIcon: 'present', weight: 6, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['living', 'workshop', 'sleeping', 'dining', 'storage', 'garage', 'chapel'] },
    { kind: 'snowman', name: 'snowman', engineType: 'statue', themeIcon: 'snowman', weight: 3, footprints: [rect(1, 1)], placement: 'centre', maxPerRoom: 2, allowedRoomTypes: ['outdoor'] },
    { kind: 'reindeer', name: 'reindeer', engineType: 'statue', themeIcon: 'reindeer', weight: 3, footprints: [rect(1, 1)], placement: 'anywhere', maxPerRoom: 3, allowedRoomTypes: ['stable', 'outdoor'] },
    { kind: 'gingerbreadHouse', name: 'gingerbread house', engineType: 'plant', themeIcon: 'gingerbreadHouse', weight: 2, footprints: [rect(1, 1)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['kitchen', 'market', 'party'] },
    { kind: 'fireplace', name: 'fireplace', engineType: 'tv', themeIcon: 'fireplace', weight: 3, footprints: [rect(1, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['living', 'dining', 'party'] },
    { kind: 'workbench', name: 'workbench', engineType: 'desk', weight: 3, footprints: [rect(2, 1), rect(3, 1, 0.6)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['workshop', 'study'] },
    { kind: 'toyShelf', name: 'toy shelf', engineType: 'bookshelf', weight: 3, footprints: [rect(1, 1), rect(2, 1)], placement: 'wall', allowedRoomTypes: ['workshop', 'sleeping', 'study', 'living'] },
    { kind: 'toyChest', name: 'toy chest', engineType: 'chest', weight: 3, footprints: [rect(1, 1)], placement: 'wall', allowedRoomTypes: ['workshop', 'sleeping', 'storage'] },
    { kind: 'wardrobe', name: 'wardrobe', engineType: 'wardrobe', weight: 2, footprints: [rect(1, 1), rect(2, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['sleeping', 'storage'] },
    { kind: 'cupboard', name: 'cupboard', engineType: 'cabinet', weight: 2, footprints: [rect(1, 1), rect(2, 1), rect(3, 1, 0.5)], placement: 'wall', allowedRoomTypes: ['kitchen', 'dining', 'storage'] },
    { kind: 'counter', name: 'counter', engineType: 'kitchenCounter', weight: 3, footprints: [rect(2, 1), rect(3, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['kitchen', 'party', 'market'] },
    { kind: 'longTable', name: 'long table', engineType: 'diningTable', weight: 3, footprints: [rect(2, 1), rect(3, 1), rect(2, 2)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['dining', 'kitchen'] },
    { kind: 'marketTable', name: 'market stall', engineType: 'gardenTable', weight: 3, footprints: [rect(1, 1), rect(2, 1), rect(2, 2, 0.5)], placement: 'centre', maxPerRoom: 3, allowedRoomTypes: ['market', 'outdoor', 'party'] },
    { kind: 'bench', name: 'bench', engineType: 'bench', weight: 4, footprints: [rect(2, 1), rect(3, 1)], placement: 'wall', allowedRoomTypes: ['chapel', 'market', 'outdoor', 'stable'] },
    { kind: 'poinsettia', name: 'poinsettia', engineType: 'flowers', weight: 5, footprints: [rect(1, 1)], placement: 'corner', allowedRoomTypes: ['living', 'dining', 'chapel', 'party'] },
    { kind: 'holly', name: 'holly', engineType: 'plant', weight: 5, footprints: [rect(1, 1)], placement: 'corner', allowedRoomTypes: ['outdoor', 'chapel', 'market'] },
    { kind: 'stairs', name: 'stairs', engineType: 'stairs', weight: 1, footprints: [rect(1, 2), rect(1, 3, 0.5), rect(2, 2, 0.4)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['storage', 'living'] },
  ],
}
