import { rect } from '../../../src/content/themes/define.ts'
import type { SeasonalTheme } from './common.ts'

/** Fall: 1-16 October, then November except the 11th. A farm, an orchard and a cabin in the woods. */
export const FALL_THEME: SeasonalTheme = {
  id: 'fall',
  name: 'Autumn farm',
  nameNl: 'Herfstboerderij',
  season: '1-16 October and November (not the 11th)',
  seasonNl: '1-16 oktober en november (niet de 11e)',
  blurb: 'Pumpkins, hay, maple leaves, cider and a campfire. Warm orange rooms, no vehicles.',
  rooms: [
    { name: 'Farmhouse Kitchen', nameNl: 'Boerderijkeuken', favours: ['counter', 'farmTable', 'rockingChair', 'pumpkin'], roomTypes: ['kitchen'], floor: 'tiles' },
    { name: 'Fireside Lounge', nameNl: 'Haardkamer', favours: ['fireplace', 'sofa', 'rockingChair', 'wovenRug'], roomTypes: ['living'], floor: 'wood' },
    { name: 'Reading Nook', nameNl: 'Leeshoek', favours: ['bookcase', 'rockingChair', 'writingDesk'], roomTypes: ['study'], floor: 'carpet' },
    { name: 'Cabin Bedroom', nameNl: 'Hutslaapkamer', favours: ['bed', 'wardrobe', 'wovenRug'], roomTypes: ['sleeping'], floor: 'carpet' },
    { name: 'Hayloft', nameNl: 'Hooizolder', favours: ['hayBale', 'bed', 'harvestCrate'], roomTypes: ['sleeping', 'farm'], floor: 'wood' },
    { name: 'Barn', nameNl: 'Schuur', favours: ['hayBale', 'harvestCrate', 'scarecrow'], roomTypes: ['storage', 'farm'], floor: 'stone' },
    { name: 'Pantry', nameNl: 'Voorraadkamer', favours: ['pantryShelves', 'harvestCrate'], roomTypes: ['storage'], floor: 'tiles' },
    { name: 'Porch', nameNl: 'Veranda', favours: ['rockingChair', 'pumpkin', 'bench', 'chrysanthemums'], roomTypes: ['outdoor', 'living'], floor: 'wood' },
    { name: 'Pumpkin Patch', nameNl: 'Pompoenenveld', favours: ['pumpkin', 'scarecrow', 'hayBale'], roomTypes: ['outdoor', 'farm'], outdoor: true, floor: 'grass' },
    { name: 'Cornfield', nameNl: 'Maisveld', favours: ['scarecrow', 'hayBale', 'leafPile'], roomTypes: ['outdoor', 'farm'], outdoor: true, floor: 'grass' },
    { name: 'Apple Orchard', nameNl: 'Appelboomgaard', favours: ['appleTree', 'leafPile', 'bench'], roomTypes: ['outdoor'], outdoor: true, floor: 'grass' },
    { name: 'Maple Lane', nameNl: 'Esdoornlaan', favours: ['mapleTree', 'leafPile', 'bench'], roomTypes: ['outdoor'], outdoor: true, floor: 'stone' },
    { name: 'Mushroom Glade', nameNl: 'Paddenstoelenbos', favours: ['mushroom', 'mapleTree', 'leafPile'], roomTypes: ['outdoor'], outdoor: true, floor: 'grass' },
    { name: 'Bonfire Meadow', nameNl: 'Kampvuurweide', favours: ['bonfire', 'leafPile', 'bench'], roomTypes: ['outdoor'], outdoor: true, floor: 'grass' },
    { name: 'Harvest Market', nameNl: 'Oogstmarkt', favours: ['counter', 'harvestTable', 'pumpkin', 'bench'], roomTypes: ['market', 'outdoor', 'farm'], outdoor: true, floor: 'stone' },
    { name: 'Cider Mill', nameNl: 'Cidermolen', favours: ['counter', 'harvestCrate', 'pantryShelves'], roomTypes: ['utility'], floor: 'wood' },
    { name: 'Greenhouse', nameNl: 'Kas', favours: ['chrysanthemums', 'mushroom', 'harvestTable'], roomTypes: ['outdoor'], floor: 'tiles' },
  ],
  objects: [
    // Occupiable
    { kind: 'rockingChair', name: 'rocking chair', engineType: 'chair', weight: 8, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['living', 'kitchen', 'study'] },
    { kind: 'hayBale', name: 'hay bale', engineType: 'rug', themeIcon: 'hayBale', weight: 5, footprints: [rect(1, 1), rect(2, 1, 0.7), rect(2, 2, 0.4)], placement: 'anywhere', allowedRoomTypes: ['farm'] },
    { kind: 'leafPile', name: 'leaf pile', engineType: 'rug', themeIcon: 'leafPile', weight: 5, footprints: [rect(1, 1), rect(2, 1, 0.7), rect(2, 2, 0.4)], placement: 'anywhere', allowedRoomTypes: ['outdoor'] },
    { kind: 'wovenRug', name: 'woven rug', engineType: 'rug', weight: 3, footprints: [rect(2, 1), rect(2, 2, 0.5)], placement: 'centre', allowedRoomTypes: ['living', 'study', 'sleeping', 'kitchen'] },
    { kind: 'bed', name: 'bed', engineType: 'bed', weight: 3, footprints: [rect(1, 2), rect(2, 2, 0.5)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['sleeping'] },
    { kind: 'sofa', name: 'sofa', engineType: 'sofa', weight: 3, footprints: [rect(2, 1), rect(3, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['living'] },
    // Blocking
    { kind: 'pumpkin', name: 'pumpkin', engineType: 'plant', themeIcon: 'pumpkin', weight: 7, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['farm', 'kitchen', 'living'] },
    { kind: 'mapleTree', name: 'maple tree', engineType: 'tree', themeIcon: 'mapleTree', weight: 6, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['outdoor'] },
    { kind: 'appleTree', name: 'apple tree', engineType: 'tree', weight: 6, footprints: [rect(1, 1)], placement: 'anywhere', allowedRoomTypes: ['outdoor'] },
    { kind: 'mushroom', name: 'toadstool', engineType: 'plant', themeIcon: 'mushroom', weight: 5, footprints: [rect(1, 1)], placement: 'corner', allowedRoomTypes: ['outdoor'] },
    { kind: 'scarecrow', name: 'scarecrow', engineType: 'statue', themeIcon: 'scarecrow', weight: 2, footprints: [rect(1, 1)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['farm'] },
    { kind: 'bonfire', name: 'bonfire', engineType: 'statue', themeIcon: 'bonfire', weight: 1.5, footprints: [rect(1, 1)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['outdoor'] },
    { kind: 'fireplace', name: 'fireplace', engineType: 'tv', themeIcon: 'fireplace', weight: 3, footprints: [rect(1, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['living'] },
    { kind: 'bookcase', name: 'bookcase', engineType: 'bookshelf', weight: 3, footprints: [rect(1, 1), rect(2, 1)], placement: 'wall', allowedRoomTypes: ['study', 'living'] },
    { kind: 'writingDesk', name: 'writing desk', engineType: 'desk', weight: 2, footprints: [rect(2, 1), rect(3, 1, 0.5)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['study'] },
    { kind: 'harvestCrate', name: 'harvest crate', engineType: 'chest', weight: 4, footprints: [rect(1, 1)], placement: 'wall', allowedRoomTypes: ['farm', 'storage', 'kitchen', 'utility'] },
    { kind: 'pantryShelves', name: 'pantry shelves', engineType: 'cabinet', weight: 3, footprints: [rect(1, 1), rect(2, 1), rect(3, 1, 0.5)], placement: 'wall', allowedRoomTypes: ['storage', 'kitchen', 'utility'] },
    { kind: 'counter', name: 'counter', engineType: 'kitchenCounter', weight: 3, footprints: [rect(2, 1), rect(3, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['kitchen', 'utility', 'market'] },
    { kind: 'farmTable', name: 'farm table', engineType: 'diningTable', weight: 3, footprints: [rect(2, 1), rect(3, 1), rect(2, 2)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['kitchen'] },
    { kind: 'harvestTable', name: 'harvest table', engineType: 'gardenTable', weight: 3, footprints: [rect(1, 1), rect(2, 1), rect(2, 2, 0.5)], placement: 'centre', maxPerRoom: 2, allowedRoomTypes: ['market', 'outdoor'] },
    { kind: 'bench', name: 'bench', engineType: 'bench', weight: 4, footprints: [rect(2, 1), rect(3, 1)], placement: 'wall', allowedRoomTypes: ['outdoor', 'market', 'living'] },
    { kind: 'chrysanthemums', name: 'chrysanthemums', clueNoun: 'chrysanthemum', engineType: 'flowers', weight: 5, footprints: [rect(1, 1)], placement: 'wall', allowedRoomTypes: ['outdoor'] },
    { kind: 'wardrobe', name: 'wardrobe', engineType: 'wardrobe', weight: 2, footprints: [rect(1, 1), rect(2, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['sleeping'] },
    { kind: 'sideTable', name: 'side table', engineType: 'table', weight: 3, footprints: [rect(1, 1), rect(2, 1, 0.5)], placement: 'centre', maxPerRoom: 1, allowedRoomTypes: ['living', 'study'] },
    { kind: 'bicycle', name: 'bicycle', engineType: 'bicycle', weight: 1.5, footprints: [rect(2, 1)], placement: 'wall', maxPerRoom: 1, allowedRoomTypes: ['outdoor', 'storage'] },
  ],
}
