/** Dutch wording of the play screen. Clue and gift wording live in engine/clues/nl.ts. */
export const PLAY_NL = {
  title: 'Slaydoku',
  tools: {
    label: 'Gereedschap',
    note: 'Notitie',
    place: 'Plaats',
    x: 'X',
    erase: 'Gum',
    undo: 'Terug',
    redo: 'Vooruit',
    hint: 'Hint',
    autoX: 'Auto-X',
    options: 'Opties',
    help: 'Uitleg',
    legend: 'Legenda',
    zoom: 'Zoom',
  },
  toolTitle: {
    note: 'Tik op een vakje voor een notitie, houd ingedrukt om te plaatsen. Sleep om meerdere vakjes te vullen.',
    place: 'Tik op een vakje om de verdachte te plaatsen, houd ingedrukt voor een notitie.',
    x: 'Tik op een vakje om het uit te sluiten. Sleep om meerdere vakjes te kruisen.',
    erase: 'Tik op een vakje om het te wissen. Houd deze knop ingedrukt om alles te wissen.',
    legend: 'Wat betekenen de spullen en tekens op dit bord?',
    zoom: 'Vergroot het bord (2x), tik nogmaals voor 1x. Met twee vingers kun je ook knijpen en schuiven.',
  },
  pickSuspect: 'Kies eerst een verdachte.',
  timerShow: 'Toon de tijd',
  timerHide: 'Verberg de tijd',
  cards: 'Verdachten',
  board: 'Plattegrond',
  options: {
    title: 'Opties',
    autoX: 'Automatisch X bij plaatsen',
    autoXHelp: 'Kruist de rij en kolom van een geplaatste persoon uit voor de anderen.',
    preventX: 'Geen X op geblokkeerde vakjes',
    preventXHelp: 'Op vakjes waar niemand kan staan (tafel, plant) komt nooit een X of notitie.',
    timer: 'Tijd tonen',
    timerHelp: 'De klok blijft lopen, ook als je hem verbergt.',
    axisLabels: 'Rij- en kolomnummers',
    axisLabelsHelp: 'R1, R2 langs de linkerkant zijn de rijen, C1, C2 boven het bord de kolommen: R3 en C4 is "rij 3, kolom 4".',
    clearAll: 'Alles wissen',
    restart: 'Opnieuw beginnen',
    restartConfirm: 'Zeker weten? Tik nogmaals',
    close: 'Sluiten',
  },
  clearConfirm: {
    title: 'Alles wissen?',
    text: 'Alle notities, X-en en geplaatste personen verdwijnen. Je kunt dit ongedaan maken met Terug.',
    yes: 'Wis alles',
    no: 'Annuleren',
  },
  hint: {
    level: (n: number) => `Hint ${n} van 3`,
    more: 'Meer hulp',
    close: 'Sluiten',
    none: 'Geen hint beschikbaar. Je staat er goed voor, of de aanwijzingen zijn op.',
    place: 'Plaats voor mij',
  },
  result: {
    solvedTitle: 'Opgelost!',
    solved: (name: string) => `${name} was alleen met het cadeau.`,
    time: (formatted: string) => `Tijd: ${formatted}`,
    wrongTitle: 'Klopt nog niet',
    wrong: (correct: number, total: number) => `Niet helemaal: ${correct} van ${total} goed, probeer opnieuw.`,
    again: 'Opnieuw spelen',
    viewBoard: 'Bekijk het bord',
    keepGoing: 'Verder puzzelen',
  },
} as const
