import { VICTIM_TEXT } from '../../engine/clues/index.ts'

/** English wording of the play screen. Clue and victim wording live in engine/clues/en.ts. */
export const PLAY_EN = {
  title: 'Slaydoku',
  tools: {
    label: 'Tools',
    mode: 'Mode',
    note: 'Note',
    place: 'Place',
    x: 'X',
    erase: 'Erase',
    undo: 'Undo',
    redo: 'Redo',
    hint: 'Hint',
    autoX: 'Auto-X',
    options: 'Options',
    help: 'Help',
    legend: 'Legend',
    zoom: 'Zoom',
  },
  toolTitle: {
    note: 'Tap a square to make a note, hold to place. Drag to fill several squares.',
    place: 'Tap a square to place the suspect, hold to make a note.',
    x: 'Tap a square to rule it out. Drag to cross several squares.',
    erase: 'Tap a square to clear it. Hold this button to clear everything.',
    legend: 'What do the objects and marks on this board mean?',
    zoom: 'Enlarge the board (2x), tap again for 1x. With two fingers you can also pinch and pan.',
  },
  pickSuspect: 'Pick a suspect first.',
  timerShow: 'Show the time',
  timerHide: 'Hide the time',
  cards: 'Suspects',
  board: 'Floor plan',
  options: {
    title: 'Options',
    autoX: 'Auto-X when placing',
    autoXHelp: 'Crosses out the row and column of a placed person for the others.',
    preventX: 'No X on blocked squares',
    preventXHelp: 'Squares where nobody can stand (table, plant) never get an X or a note.',
    timer: 'Show time',
    timerHelp: 'The clock keeps running, even when you hide it.',
    axisLabels: 'Row and column numbers',
    axisLabelsHelp: 'R1, R2 along the left are the rows, C1, C2 above the board are the columns: R3 and C4 is "row 3, column 4".',
    clearAll: 'Clear all',
    restart: 'Start over',
    restartConfirm: 'Sure? Tap again',
    close: 'Close',
  },
  clearConfirm: {
    title: 'Clear everything?',
    text: 'All notes, Xs and placed people disappear. You can undo this with Undo.',
    yes: 'Clear all',
    no: 'Cancel',
  },
  hint: {
    level: (n: number) => `Hint ${n} of 3`,
    more: 'More help',
    close: 'Close',
    none: 'No hint available. You are doing well, or the clues have run out.',
    place: 'Place for me',
  },
  result: {
    solvedTitle: 'Solved!',
    solved: (name: string) => `You found the murderer! ${name} was alone with ${VICTIM_TEXT.noun}.`,
    time: (formatted: string) => `Time: ${formatted}`,
    wrongTitle: 'Not right yet',
    wrong: (correct: number, total: number) => `Not quite: ${correct} of ${total} correct, try again.`,
    again: 'Play again',
    viewBoard: 'View the board',
    keepGoing: 'Keep going',
  },
} as const
